# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nyx_post.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nyx_post.proto", :syntax => :proto3) do
    add_message "nyx.GetRequest" do
      optional :title, :string, 1
      optional :description, :string, 2
    end
    add_message "nyx.GetReply" do
      optional :message, :string, 1
    end
    add_message "nyx.CreateRequest" do
    end
    add_message "nyx.CreateReply" do
    end
    add_message "nyx.DeleteRequest" do
    end
    add_message "nyx.DeleteReply" do
    end
    add_message "nyx.UpdateRequest" do
    end
    add_message "nyx.UpdateReply" do
    end
  end
end

module Nyx
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetRequest").msgclass
  GetReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetReply").msgclass
  CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.CreateRequest").msgclass
  CreateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.CreateReply").msgclass
  DeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.DeleteRequest").msgclass
  DeleteReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.DeleteReply").msgclass
  UpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.UpdateRequest").msgclass
  UpdateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.UpdateReply").msgclass
end
