# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nyx_post.proto for package 'nyx'

require 'grpc'
require_relative 'nyx_post_pb'

module Nyx
  module PostService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'nyx.PostService'

      rpc :GetPost, ::Nyx::GetPostRequest, ::Nyx::GetPostReply
      rpc :GetPosts, ::Nyx::GetPostsRequest, ::Nyx::GetPostsReply
      rpc :Create, ::Nyx::CreateRequest, ::Nyx::CreateReply
      rpc :Delete, ::Nyx::DeleteRequest, ::Nyx::DeleteReply
      rpc :Update, ::Nyx::UpdateRequest, ::Nyx::UpdateReply
    end

    Stub = Service.rpc_stub_class
  end
end
