# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nyx_post.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nyx_post.proto", :syntax => :proto3) do
    add_message "nyx.Post" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :description, :string, 3
    end
    add_message "nyx.GetPostRequest" do
      optional :id, :string, 1
    end
    add_message "nyx.GetPostReply" do
      optional :post, :message, 1, "nyx.Post"
    end
    add_message "nyx.GetPostsRequest" do
      optional :skip, :uint64, 1
      optional :take, :uint64, 2
    end
    add_message "nyx.GetPostsReply" do
      repeated :posts, :message, 1, "nyx.Post"
    end
    add_message "nyx.CreateRequest" do
      optional :title, :string, 1
      optional :description, :string, 2
    end
    add_message "nyx.CreateReply" do
      optional :message, :string, 1
    end
    add_message "nyx.DeleteRequest" do
    end
    add_message "nyx.DeleteReply" do
    end
    add_message "nyx.UpdateRequest" do
    end
    add_message "nyx.UpdateReply" do
    end
  end
end

module Nyx
  Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.Post").msgclass
  GetPostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetPostRequest").msgclass
  GetPostReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetPostReply").msgclass
  GetPostsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetPostsRequest").msgclass
  GetPostsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.GetPostsReply").msgclass
  CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.CreateRequest").msgclass
  CreateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.CreateReply").msgclass
  DeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.DeleteRequest").msgclass
  DeleteReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.DeleteReply").msgclass
  UpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.UpdateRequest").msgclass
  UpdateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("nyx.UpdateReply").msgclass
end
